// ─────────────────────────────────────────────────────────────────────────────
//  Portfolio OS — data entry for the "DevOps" folder
//
//  This object matches the portfolio's `Project` type
//  (frontend/src/types.ts) and renders inside the "DevOps" folder window.
//
//  Two ways to add it to your portfolio:
//
//  1. Recommended (already done): the same entry was added to
//     `frontend/src/data/initialData.ts` under INITIAL_PROJECTS.
//     The app merges new seed projects into existing localStorage on next load,
//     so it appears automatically — no data is overwritten.
//
//  2. Via the UI: right-click the desktop → New → Portfolio Project (UAC-gated),
//     then paste the fields below into the "DevOps" folder.
// ─────────────────────────────────────────────────────────────────────────────

import type { Project } from '../src/types';

export const DEVOPS_PIPELINE_PROJECT: Project = {
  id: 'proj-devops-pipeline',
  title: 'AWS Production CI/CD Pipeline & Cloud Deployment (FidaBet)',
  tagline:
    'Automated GitHub Actions CI/CD deploying Spring Boot & Next.js microservices to Amazon ECR and AWS EC2 with IAM security and Docker Desktop verification.',
  description: [
    'Comprehensive production DevOps engineering and automated delivery pipeline for FidaBet (betting-with-fida-auth). The solution integrates automated containerization, private Amazon ECR registries, least-privilege AWS IAM security governance, and zero-downtime rolling deployments to an AWS EC2 instance on every push to the main branch.',
    '',
    '▸ 1. AWS IAM Security & Access Governance (AWS Account: 933858446201)',
    '  • Enforced root account security: root user has 0 active access keys; MFA actively enabled.',
    '  • Provisioned a dedicated CI/CD IAM automation user with least-privilege scoped policies for ECR push and EC2 SSH rollout.',
    '  • Configured 5 IAM roles for service execution & instance profiles, plus 1 OpenID Connect (OIDC) identity provider.',
    '',
    '▸ 2. Amazon Elastic Container Registry (ECR — us-east-1)',
    '  • Provisioned private repositories: backend-springboot and frontend in US East (N. Virginia).',
    '  • Registry URIs: 933858446201.dkr.ecr.us-east-1.amazonaws.com/backend-springboot & 933858446201.dkr.ecr.us-east-1.amazonaws.com/frontend.',
    '  • Enforced mutable release tags with Git commit SHA versioning, vulnerability scanning, and server-side encryption.',
    '',
    '▸ 3. Docker Containerization & Local Pre-Deployment Verification',
    '  • Multi-stage Dockerfile architecture producing lightweight production containers: Spring Boot backend (324 MB), Next.js frontend (108 MB), Postgres 16 Alpine (419 MB), and Redis 7 Alpine (57 MB).',
    '  • Local verification stack: verify-backend (port 18080:8080) and verify-postgres containers running in Docker Desktop with resource telemetry (0.83% CPU, 289 MB RAM) to validate schema migrations and CORS prior to push.',
    '',
    '▸ 4. GitHub Actions Automated CI/CD (Workflow: Deploy to AWS EC2)',
    '  • 16 automated workflow runs across commits (CORS origin fixes, H2/PostgreSQL data directory permissions, EC2 deployment automation).',
    '  • 12-stage automated pipeline completing in 2m 28s on push to main.',
    '',
    '▸ 5. AWS EC2 Production Server (Instance: hagerawi — us-east-1c)',
    '  • Production host: AWS EC2 t3.micro instance running in Availability Zone us-east-1c.',
    '  • Status: 3/3 checks passed (System check, Instance check, Attached volume check) with 0 alarms and healthy operational status.',
    '  • Executes Docker Compose rolling rollout with zero-downtime recreation and automatic container health checks.',
  ].join('\n'),
  folderId: 'folder-devops',
  tags: ['DevOps', 'AWS EC2', 'Amazon ECR', 'GitHub Actions', 'Docker', 'Spring Boot', 'PostgreSQL', 'IAM', 'CI/CD'],
  techStack: [
    'AWS EC2 (t3.micro)',
    'Amazon ECR',
    'AWS IAM (Least Privilege)',
    'GitHub Actions CI/CD',
    'Docker Desktop & Compose',
    'Spring Boot 3',
    'PostgreSQL 16 Alpine',
    'Redis 7 Alpine',
    'Next.js / React',
    'Maven 3.9',
    'Nginx Reverse Proxy',
    'SSH Deploy Automation',
  ],
  githubUrl: 'https://github.com/yonialt/betting-with-fida-auth',
  imageUrl: '/assets/projects/devops-aws-pipeline.jpg',
  featured: true,
  createdAt: '2026-08-13T10:00:00.000Z',
  updatedAt: '2026-09-17T10:00:00.000Z',
  steps: [
    {
      number: 1,
      title: 'Set up job',
      duration: '2s',
      status: 'success',
      description: 'Initialize GitHub-hosted runner virtual environment.',
      details: [
        'Operating System: Ubuntu 22.04 LTS runner environment',
        'Sets up runner execution context, virtual network, and GitHub Actions workflow tokens',
        'Restores action dependency caches',
      ],
    },
    {
      number: 2,
      title: 'Checkout repository',
      duration: '1s',
      status: 'success',
      description: 'Fetch latest application source code from GitHub.',
      command: 'actions/checkout@v4',
      details: [
        'Target repository: yonialt/betting-with-fida-auth',
        'Checked out target branch: main at commit SHA',
        'Fetches full Git commit metadata and repository history',
      ],
    },
    {
      number: 3,
      title: 'Configure AWS credentials',
      duration: '1s',
      status: 'success',
      description: 'Authenticate workflow runner with AWS using least-privilege IAM credentials.',
      command: 'aws-actions/configure-aws-credentials@v4',
      details: [
        'AWS Account ID: 933858446201 (IAM User with scoped policies)',
        'AWS Region: us-east-1 (US East N. Virginia)',
        'Root account protected with MFA & 0 active root keys; CI uses dedicated IAM automation credentials',
      ],
    },
    {
      number: 4,
      title: 'Login to Amazon ECR',
      duration: '0s',
      status: 'success',
      description: 'Authenticate local runner Docker daemon with AWS Elastic Container Registry.',
      command: 'aws-actions/amazon-ecr-login@v2',
      details: [
        'Private Registry: 933858446201.dkr.ecr.us-east-1.amazonaws.com',
        'Obtains temporary Docker authorization token via AWS STS / IAM',
        'Enables authenticated Docker push for frontend and backend repositories',
      ],
    },
    {
      number: 5,
      title: 'Set deployment tag',
      duration: '0s',
      status: 'success',
      description: 'Generate immutable build and release tags for image versioning.',
      command: 'echo "DEPLOY_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV',
      details: [
        'Computes short Git commit hash and automated timestamp',
        'Applies dual-tag strategy: :latest for production pointer and :<commit-sha> for immutable traceability',
      ],
    },
    {
      number: 6,
      title: 'Build and push frontend image',
      duration: '37s',
      status: 'success',
      description: 'Multi-stage production build and push of Next.js/React frontend.',
      command: 'docker build -t 933858446201.dkr.ecr.us-east-1.amazonaws.com/frontend:latest ./frontend && docker push',
      details: [
        'Multi-stage Dockerfile: Node build stage with dependency pruning, outputting standalone static artifacts',
        'Target image: 933858446201.dkr.ecr.us-east-1.amazonaws.com/frontend:latest (108.34 MB)',
        'Pushed to Amazon ECR private repository in 37 seconds',
      ],
    },
    {
      number: 7,
      title: 'Build and push backend image',
      duration: '1m 20s',
      status: 'success',
      description: 'Maven compilation and container packaging of Spring Boot microservice.',
      command: 'docker build -t 933858446201.dkr.ecr.us-east-1.amazonaws.com/backend-springboot:latest ./backend && docker push',
      details: [
        'Build stage utilizes maven:3.9-eclipse-temurin base image to compile and run automated unit tests',
        'Packages optimized JRE runtime container (324.72 MB) with production application profiles',
        'Pushed to Amazon ECR private repository in 1 minute 20 seconds',
      ],
    },
    {
      number: 8,
      title: 'Deploy to EC2',
      duration: '24s',
      status: 'success',
      description: 'Remote SSH zero-downtime rolling update on AWS EC2 server.',
      command: 'ssh -i ec2.pem ec2-user@hagerawi "docker compose pull && docker compose up -d --remove-orphans"',
      details: [
        'Production Target: AWS EC2 instance "hagerawi" (t3.micro, us-east-1c, 3/3 checks passed)',
        'Authenticates with Amazon ECR on the remote host',
        'Pulls freshly published backend & frontend container images',
        'Executes rolling docker compose recreation with persistent PostgreSQL volume mappings and health probes',
      ],
    },
    {
      number: 9,
      title: 'Post Login to Amazon ECR',
      duration: '0s',
      status: 'success',
      description: 'Revoke temporary Amazon ECR authentication tokens from the runner.',
      details: [
        'Logs out Docker daemon from 933858446201.dkr.ecr.us-east-1.amazonaws.com',
        'Prevents credential leakage across runner stages',
      ],
    },
    {
      number: 10,
      title: 'Post Configure AWS credentials',
      duration: '0s',
      status: 'success',
      description: 'Unset AWS session tokens and credentials from runner environment.',
      details: [
        'Clears AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and session environment variables',
        'Zeroes memory credentials following security best practices',
      ],
    },
    {
      number: 11,
      title: 'Post Checkout repository',
      duration: '0s',
      status: 'success',
      description: 'Purge workspace checkout and temporary build artifacts.',
      details: [
        'Removes temporary Git working trees and build caches from runner workspace',
      ],
    },
    {
      number: 12,
      title: 'Complete job',
      duration: '0s',
      status: 'success',
      description: 'Final execution validation and workflow success confirmation.',
      details: [
        'Total pipeline duration: 2m 28s across all 12 steps',
        'Emits green check status to GitHub repository yonialt/betting-with-fida-auth',
        'Production services live and verified on AWS EC2 host "hagerawi"',
      ],
    },
  ],
};

export const DEVOPS_IAM_SECURITY_PROJECT: Project = {
  id: 'proj-devops-iam-security',
  title: 'AWS IAM Security Governance & Access Control',
  tagline: 'AWS Account 933858446201 security posture: root MFA enforced, 0 active root keys, and scoped CI/CD service credentials.',
  description: [
    'Security governance and identity management for the FidaBet cloud infrastructure in AWS IAM (Account ID: 933858446201).',
    '',
    '▸ Root Account Security & Hardening',
    '  • Root user has 0 active access keys, mitigating the risk of programmatic credential leakage.',
    '  • Multi-Factor Authentication (MFA) is actively configured and enforced on the root account.',
    '  • Follows AWS Well-Architected Framework security pillar standards.',
    '',
    '▸ CI/CD Automation IAM Identity',
    '  • Dedicated CI/CD automation IAM user provisioned for GitHub Actions runner authentication.',
    '  • Scoped least-privilege IAM policies restricting actions strictly to Amazon ECR authorization/push and EC2 deployment execution.',
    '',
    '▸ Role Architecture & Identity Providers',
    '  • 5 configured IAM service roles for instance profiles and background execution.',
    '  • 1 OpenID Connect (OIDC) identity provider integrated for secure external authentication without long-lived secrets.',
  ].join('\n'),
  folderId: 'folder-devops',
  tags: ['AWS IAM', 'Security', 'Cloud Governance', 'MFA', 'OIDC', 'DevOps'],
  techStack: [
    'AWS IAM',
    'Account: 933858446201',
    'Multi-Factor Auth (MFA)',
    'Least-Privilege Policies',
    '5 IAM Roles',
    'OIDC Provider',
  ],
  githubUrl: 'https://github.com/yonialt/betting-with-fida-auth',
  featured: true,
  createdAt: '2026-08-13T10:00:00.000Z',
  updatedAt: '2026-09-17T10:00:00.000Z',
};

export const DEVOPS_ECR_REGISTRY_PROJECT: Project = {
  id: 'proj-devops-ecr-registry',
  title: 'Amazon ECR Microservices Container Registry',
  tagline: 'Private Docker repositories in us-east-1 storing Spring Boot backend and Next.js frontend production images with AES-256 encryption.',
  description: [
    'Centralized container registry infrastructure hosted on Amazon Elastic Container Registry (ECR) in region us-east-1 (US East - N. Virginia).',
    '',
    '▸ Registry & Repositories (URI: 933858446201.dkr.ecr.us-east-1.amazonaws.com)',
    '  • backend-springboot: Private repository storing Spring Boot 3 REST API production images.',
    '  • frontend: Private repository storing Next.js / React web client production images.',
    '',
    '▸ Security & Tagging Strategy',
    '  • Server-Side Encryption: AES-256 encryption enabled across all repository layers.',
    '  • Tag Mutability: Configured for release tagging with dual pointer support (:latest and immutable :<commit-sha>).',
    '  • Vulnerability Scanning: Automated basic vulnerability scanning enabled on image push to detect package CVEs before production deployment.',
  ].join('\n'),
  folderId: 'folder-devops',
  tags: ['Amazon ECR', 'AWS us-east-1', 'Docker Registry', 'Microservices', 'DevOps'],
  techStack: [
    'Amazon ECR (us-east-1)',
    'URI: 933858446201.dkr.ecr.us-east-1.amazonaws.com',
    'AES-256 Encryption',
    'backend-springboot',
    'frontend',
    'Docker V2 API',
  ],
  githubUrl: 'https://github.com/yonialt/betting-with-fida-auth',
  featured: true,
  createdAt: '2026-08-13T10:00:00.000Z',
  updatedAt: '2026-09-17T10:00:00.000Z',
};

export const DEVOPS_DOCKER_IMAGES_PROJECT: Project = {
  id: 'proj-devops-docker-images',
  title: 'Docker Multi-Stage Build & Container Image Optimization',
  tagline: 'Production multi-stage build optimization reducing Spring Boot backend to 324 MB and Next.js frontend to 108 MB.',
  description: [
    'Containerization architecture utilizing multi-stage Dockerfiles to minimize production attack surfaces and container footprints in Docker Desktop.',
    '',
    '▸ Image Inventory & Size Metrics',
    '  • betting-with-fida-auth-fidabet-backend:latest / fidabet-backend:verify: 324.72 MB (compiled using maven:3.9-eclipse-temurin, stripped to lean Temurin JRE 17 runtime layer).',
    '  • betting-with-fida-auth-fidabet-frontend:latest: 108.34 MB (multi-stage Node build generating standalone static artifacts).',
    '  • Supporting Microservices: postgres:16-alpine (419.68 MB) and redis:7-alpine (57.82 MB).',
    '',
    '▸ Benefits of Multi-Stage Architecture',
    '  • Excludes Maven compiler dependencies, Node build tools, and source code from final images.',
    '  • Speeds up Amazon ECR push and pull times over network interfaces.',
    '  • Decreases container cold-start latency and EC2 memory consumption.',
  ].join('\n'),
  folderId: 'folder-devops',
  tags: ['Docker', 'Multi-Stage Builds', 'Spring Boot', 'Next.js', 'Alpine Linux', 'Containerization'],
  techStack: [
    'Docker Desktop',
    'Multi-Stage Dockerfiles',
    'Maven 3.9 Eclipse Temurin',
    'JRE 17 Alpine',
    'Postgres 16 Alpine',
    'Redis 7 Alpine',
  ],
  githubUrl: 'https://github.com/yonialt/betting-with-fida-auth',
  featured: true,
  createdAt: '2026-08-13T10:00:00.000Z',
  updatedAt: '2026-09-17T10:00:00.000Z',
};

export const DEVOPS_DOCKER_CONTAINERS_PROJECT: Project = {
  id: 'proj-devops-docker-containers',
  title: 'Docker Desktop Local Verification & Pre-Deployment Stack',
  tagline: 'Pre-deployment local verification environment running Spring Boot (port 18080:8080) and PostgreSQL 16 with live resource telemetry.',
  description: [
    'Local staging and verification stack orchestrated in Docker Desktop to validate application changes, database migrations, and CORS configurations prior to remote cloud deployment.',
    '',
    '▸ Running Service Topology',
    '  • verify-backend: Spring Boot microservice running on port 18080:8080.',
    '  • verify-postgres: PostgreSQL 16 Alpine container with isolated bridge network connectivity.',
    '  • betting-with-fida-auth stack: Integrated multi-service Compose environment.',
    '',
    '▸ Verification Telemetry & Health Diagnostics',
    '  • Real-time resource usage monitored at 0.83% CPU and 289.91 MB memory footprint under active verification load.',
    '  • Verifies database schema migrations, connection pooling, environment secrets, and CORS headers before triggering remote AWS CI/CD pipelines.',
  ].join('\n'),
  folderId: 'folder-devops',
  tags: ['Docker Desktop', 'Local Staging', 'PostgreSQL', 'Port Forwarding', 'Live Telemetry'],
  techStack: [
    'Docker Desktop',
    'verify-backend (18080:8080)',
    'verify-postgres (5432)',
    'CPU / RAM Telemetry',
    'Docker Compose',
    'Health Probes',
  ],
  githubUrl: 'https://github.com/yonialt/betting-with-fida-auth',
  featured: true,
  createdAt: '2026-08-13T10:00:00.000Z',
  updatedAt: '2026-09-17T10:00:00.000Z',
};

export const DEVOPS_GITHUB_ACTIONS_HISTORY_PROJECT: Project = {
  id: 'proj-devops-github-actions-history',
  title: 'GitHub Actions CI/CD Pipeline Execution History',
  tagline: '16 automated CI/CD workflow runs for "Deploy to AWS EC2" tracking commits, bug fixes, and continuous delivery.',
  description: [
    'Continuous Integration and Delivery audit log tracking 16 automated workflow runs for the "Deploy to AWS EC2" pipeline in repository yonialt/betting-with-fida-auth.',
    '',
    '▸ Automated Delivery Governance',
    '  • 16 automated runs executing on git push and pull request events to main.',
    '  • Commits tracked include production CORS origin fixes, H2 and PostgreSQL data directory permissions, and Docker Compose rolling deploy automation.',
    '  • 100% green execution checkmarks enforcing build, test, and container packaging quality gates prior to remote EC2 deployment.',
  ].join('\n'),
  folderId: 'folder-devops',
  tags: ['GitHub Actions', 'CI/CD History', 'GitOps', 'Automation', 'DevOps'],
  techStack: [
    'GitHub Actions',
    'Workflow: Deploy to AWS EC2',
    'Repository: yonialt/betting-with-fida-auth',
    '16 Automated Runs',
    'Git Branch: main',
  ],
  githubUrl: 'https://github.com/yonialt/betting-with-fida-auth',
  featured: true,
  createdAt: '2026-08-13T10:00:00.000Z',
  updatedAt: '2026-09-17T10:00:00.000Z',
};

export const DEVOPS_GITHUB_ACTIONS_STEPS_PROJECT: Project = {
  id: 'proj-devops-github-actions-steps',
  title: 'GitHub Actions 12-Step Automated Production Deployment',
  tagline: 'Detailed 12-stage automated cloud deployment pipeline completing runner setup, Docker build/push, and EC2 rollout in 2m 28s.',
  description: [
    'Complete 12-step automated continuous deployment pipeline executing under GitHub Actions (.github/workflows/deploy.yml) for repository yonialt/betting-with-fida-auth.',
    '',
    '▸ Pipeline Execution Overview (Total Duration: 2m 28s)',
    '  1. Set up job (2s) — Runner environment initialization on Ubuntu 22.04 LTS.',
    '  2. Checkout repository (1s) — actions/checkout@v4 on branch main at latest commit SHA.',
    '  3. Configure AWS credentials (1s) — aws-actions/configure-aws-credentials@v4 with scoped IAM credentials.',
    '  4. Login to Amazon ECR (0s) — aws-actions/amazon-ecr-login@v2 against private registry.',
    '  5. Set deployment tag (0s) — Generates short commit SHA and release timestamp.',
    '  6. Build and push frontend image (37s) — Next.js production build pushed to ECR (108.34 MB).',
    '  7. Build and push backend image (1m 20s) — Maven build and Temurin Spring Boot container pushed to ECR (324.72 MB).',
    '  8. Deploy to EC2 (24s) — Remote SSH rolling update on AWS EC2 host hagerawi via Docker Compose.',
    '  9-12. Post steps & Completion (0s) — ECR logout, credential cleanup, workspace purge, and status check confirmation.',
  ].join('\n'),
  folderId: 'folder-devops',
  tags: ['GitHub Actions', 'Pipeline Stages', 'AWS EC2', 'Amazon ECR', 'Automation', 'DevOps'],
  techStack: [
    'GitHub Actions',
    'actions/checkout@v4',
    'aws-actions/configure-aws-credentials@v4',
    'aws-actions/amazon-ecr-login@v2',
    'Docker Push',
    'SSH Remote Deploy',
  ],
  githubUrl: 'https://github.com/yonialt/betting-with-fida-auth',
  featured: true,
  createdAt: '2026-08-13T10:00:00.000Z',
  updatedAt: '2026-09-17T10:00:00.000Z',
  steps: DEVOPS_PIPELINE_PROJECT.steps,
};

export const DEVOPS_EC2_SERVER_PROJECT: Project = {
  id: 'proj-devops-ec2-server',
  title: 'AWS EC2 Production Cloud Server (Instance: hagerawi)',
  tagline: 'Production t3.micro server in us-east-1c running containerized microservices with 3/3 checks passed and zero alarms.',
  description: [
    'Production cloud server infrastructure running on Amazon Elastic Compute Cloud (EC2) in Availability Zone us-east-1c (US East - N. Virginia).',
    '',
    '▸ Server Specifications & Status',
    '  • Instance Name: hagerawi',
    '  • Instance Type: t3.micro (2 vCPUs, burstable compute, EBS-optimized)',
    '  • Availability Zone: us-east-1c',
    '  • Operational Health: 3/3 checks passed (System reachability check, Instance status check, Attached EBS volume reachability check).',
    '  • Alarms: 0 active alarms; instance is in a green, fully operational running state.',
    '',
    '▸ Production Deployment Execution',
    '  • Remote host executes Docker Compose rolling updates triggered securely via GitHub Actions SSH deployment.',
    '  • Persistent PostgreSQL EBS storage volumes ensure zero data loss across container lifecycle transitions.',
    '  • Automatic restart policies ensure 24/7 service availability for all backend and frontend services.',
  ].join('\n'),
  folderId: 'folder-devops',
  tags: ['AWS EC2', 't3.micro', 'Production Server', 'Cloud Compute', 'DevOps'],
  techStack: [
    'AWS EC2',
    'Instance: hagerawi',
    'Type: t3.micro',
    'Zone: us-east-1c',
    'Status: 3/3 Checks Passed',
    '0 Alarms',
    'Docker Compose',
    'EBS Volume',
  ],
  githubUrl: 'https://github.com/yonialt/betting-with-fida-auth',
  featured: true,
  createdAt: '2026-08-13T10:00:00.000Z',
  updatedAt: '2026-09-17T10:00:00.000Z',
};

export const ALL_DEVOPS_PROJECTS: Project[] = [
  DEVOPS_PIPELINE_PROJECT,
  DEVOPS_IAM_SECURITY_PROJECT,
  DEVOPS_ECR_REGISTRY_PROJECT,
  DEVOPS_DOCKER_IMAGES_PROJECT,
  DEVOPS_DOCKER_CONTAINERS_PROJECT,
  DEVOPS_GITHUB_ACTIONS_HISTORY_PROJECT,
  DEVOPS_GITHUB_ACTIONS_STEPS_PROJECT,
  DEVOPS_EC2_SERVER_PROJECT,
];
